[template]
src   = "kibana-config.conf.tmpl"
dest  = "/opt/kibana-3.1.0/config.js"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "elasticsearch/host"
]
#check_cmd  = "nginx -t -c /etc/nginx/nginx.conf"
#reload_cmd = "nginx -s reload"
