[template]
src   = "nginx.conf.tmpl"
dest  = "/etc/nginx/sites-enabled/nginx"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "elasticsearch/host"
]
check_cmd  = "nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "nginx -s reload"
